---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homely-mqtt
  namespace: default
  labels:
    app: homely-mqtt
spec:
  encryptedData:
    HOMELY__PASSWORD: AgCpiLjQIJ03F1s4BRC7z8Xmj8D/c7Ca9EHyUw1Vq214SxYtY3pSIwYXshCsrhhKfbrWnw7IcClPiaN3NC19bJS1QNuPG6n8DBZeubd3DITU4j6Q+Nx7BShYilJFlg2OmyKDqFYf/w3rCEQnzeP3eDPcp/YAAt48DtD+yhIa3+LeTlYjJwV957+IA6JQb50butB5xB2kM2c77yY7/6Ut7Amyd5vur+vcrjfUrMnDlF2hb6qXYMSX3c2wW4FzdoAt1p830fUws5HqOnP117V6e6pRAkQCBVblaAH5NJ5TAK6zAtRRX/VGQTiHxALJrCjdUs9gVO620NXBx7PiDvGbhyzaQCTS1wjSDhLet1ErMlq/+jdh1MxFvh6LB4tWrA7w3CBHt6r0whVB0LWBUqgPE6MHpYUa5VzQk6VuGJScnpSQPDdmtNNzf9ss9TsivTkq3FITUrRXXEa1LNUo91w4hmlr8NCjnonBL32ZbgTWxqMBTj0CffmaAUKOJr6l8O3spxaC5M6PRLs8IRMc/vKGKH0rRQ3Pu3sUrJKAyB7zqmK0AFqIZ9s3lVVXerReTrADuhKgS6no0aURcFI3SyiipwKYKJGhozxIIbOR6KKxFqIrby4tyIusu2we/SxAhiyBz7KyMao3Ad73Rjk+Eizx6NGOCe1KJvfeqBHw67ri+mcyBO4+7lnPhlBCQZV4yK2UW4f7w6SLJrvJ7/d4Ws8akwm158/z+g==
    HOMELY__USERNAME: AgDfOZqQaKx0FmiKLAl3528KK+rumBBPFxXaPehtyxe1o1yKTFDY4gLhK6zlFVjUPcKNVWA06ZJe24IIQNLDRp2fegUvR3LGJ+yWvfNpyAffsgVH9I9G14S++j3lLaW1Naky2Rm/GViPIYZSZ3quXr95ZUBPzE7gqhHGn01YWnnI0gOYQ/o55kIwPvO6kOWsMEs0NF0sxXpLedslWaJK5AYLt3Uejj4aGGovdgw2KUUu1JFcIT0Utriku66cSKH1YzYdCXjclCVIAGMjP1QJ7fffoh0r6lt5OSaWASbPm/Tw9YtOlpx2zfJIpgGBKovxVwuBuEo6cac2a3DD5wE286IqAdyZ6GqbFznXJnZOoUKu2nwUTDHebo/Eecj9P4IdFByf/sKwt1+asnqxY07MjQPoE24GK9oWmEM4uX2z4xXaKKxSAXQkYUjtuC4uzy19kwNUGC9EapCiSYOQ0g7Jm//o92MKhGbJPZi3tcV8g68bmGCdLO8CqfWipUTvj+GvpMxgNSXO+HJQR2EH80vIN9oeNw5UZWGTi3BKDfsgs7tQkzlOfR5nWMdiUi8/4DA32uZXuXSaXmTxL87Rp4/U8BqbOg8NTasSfaFc4zA/CimDmV5NXg5scaX8JrPGTBraz9Tly/iWl5fuF/ci5ndZWPiOOWNYIpQ2vX+v4ZZFWH8z8yHM+TO7K8FcfC9A4yWwmg4lwIwY767rYYlVoat2NQax9iTd
  template:
    metadata:
      name: homely-mqtt
      namespace: default
      labels:
        app: homely-mqtt
    type: Opaque
